name: Release App

on:
  push:
    branches:
      - dev

concurrency:
  group: release-ci-group
  cancel-in-progress: true

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Get npm cache directory
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn

      - name: Make Linux
        run: yarn make

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: out/make/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Renderer Bundle Stats
        uses: vio/bundle-stats-action@v1.3.0
        with:
          id: renderer
          webpack-stats-path: "out/webpack-stats-renderer.json"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Main Bundle Stats
        uses: vio/bundle-stats-action@v1.3.0
        with:
          id: main
          webpack-stats-path: "out/webpack-stats-main.json"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
